<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'BK2K\\BootstrapPackage\\DataProcessing\\FlexFormProcessor' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/DataProcessing/FlexFormProcessor.php',
    'BK2K\\BootstrapPackage\\DataProcessing\\MenuProcessor' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/DataProcessing/MenuProcessor.php',
    'BK2K\\BootstrapPackage\\Hooks\\PageRenderer\\PreProcessHook' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Hooks/PageRenderer/PreProcessHook.php',
    'BK2K\\BootstrapPackage\\Hooks\\TceMain\\ClearCacheHook' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Hooks/TceMain/ClearCacheHook.php',
    'BK2K\\BootstrapPackage\\Service\\CompileService' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Service/CompileService.php',
    'BK2K\\BootstrapPackage\\Service\\InstallService' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Service/InstallService.php',
    'BK2K\\BootstrapPackage\\Utility\\ExternalMediaUtility' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Utility/ExternalMediaUtility.php',
    'BK2K\\BootstrapPackage\\Utility\\TextIconUtility' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Utility/TextIconUtility.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\ContextualClassViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/ContextualClassViewHelper.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\DataRelationViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/DataRelationViewHelper.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\ExplodeViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/ExplodeViewHelper.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\ExternalMediaViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/ExternalMediaViewHelper.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\FalViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/FalViewHelper.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\LastImageInfoViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/LastImageInfoViewHelper.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\VarViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/VarViewHelper.php',
    'Documentation\\Examples\\Controller\\CollectionController' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/Controller/CollectionController.php',
    'Documentation\\Examples\\Controller\\ErrorController' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/Controller/ErrorController.php',
    'Documentation\\Examples\\Controller\\FalExampleController' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/Controller/FalExampleController.php',
    'Documentation\\Examples\\Controller\\HtmlParserController' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/Controller/HtmlParserController.php',
    'Documentation\\Examples\\Controller\\ModuleController' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/Controller/ModuleController.php',
    'Documentation\\Examples\\Controller\\PlusMinusWizardController' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/Controller/PlusMinusWizardController.php',
    'Documentation\\Examples\\Service\\ContextMenuOptions' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/Service/ContextMenuOptions.php',
    'Documentation\\Examples\\Service\\RteTransformation' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/Service/RteTransformation.php',
    'Documentation\\Examples\\Userfuncs\\Tca' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/Userfuncs/Tca.php',
    'Documentation\\Examples\\ViewHelpers\\Be\\EditLinkViewHelper' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/ViewHelpers/Be/EditLinkViewHelper.php',
    'Documentation\\Examples\\Xclass\\NewRecordController' => $typo3InstallDir . 'typo3conf/ext/examples/Classes/Xclass/NewRecordController.php',
);
